repository:
  default_branch: master
branches:
- name: master
  protection:
    required_status_checks: null
    enforce_admins: false
    required_pull_request_reviews:
      dismissal_restrictions: {}
      require_code_owner_reviews: true
      required_approving_review_count: 1
    restrictions: null
